!* Input file for uFEM 0.2.40 and above
!*
!* Simple 2D wall (plane stress in xy)
!*
!* File: wall.mac
!* Date: Sat Jun 28 21:27:44 CEST 2008

cleardata
jobname,test-wall

et,1,2

rs,1,2
r,height, 1, 0.01 !* thickness

mat,1,1
mp,ex,  1, 20e9
mp,prxy,1, 0.2

gesize,2,1,0,0,0,8,4  !* rectangel 8x4 m
gediv,1, 20,10        !* division
mesh                  !* f.e. mesh

!* suports on sides:
nsel,s,loc,x,0
nsel,add,loc,x,8
d,all,ux
d,all,uy

!* forces on top edge:
nsel,inve
nsel,r,loc,y,4
f,all,fy,-10e3

save

solve

pldef     !* deformations
plrs      !* reactions
ples,s_x  !* normal stresses in x direction
